package qb

const (
	SelectFragment            = "SELECT "
	DistinctFragment          = "DISTINCT "
	JsonFragment              = "JSON "
	IfNotExistsFragment       = " IF NOT EXISTS"
	FromFragment              = " FROM "
	LimitFragment             = " LIMIT "
	PerPartitionLimitFragment = " PER PARTITION LIMIT "
	GroupByFragment           = " GROUP BY "
	OrderByFragment           = " ORDER BY "
	DirectionAscFragment      = " ASC"
	DirectionDescFragment     = " DESC"
	WhereFragment             = " WHERE "
	AllowFilteringFragment    = " ALLOW FILTERING"
	AndFragment               = " AND "
	SpaceFragment             = " "
	WritetimeFragment         = "WRITETIME"
	MaxWritetimeFragment      = "MAXWRITETIME"
	TTLFragment               = "TTL"
	TimestampFragment         = "TIMESTAMP"
	OpenParenFragment         = "("
	CloseParenFragment        = ")"
	UsingFragment             = " USING "
)
