package qb

const (
	selectFragment            = "SELECT "
	distinctFragment          = "DISTINCT "
	jsonFragment              = "JSON "
	ifNotExistsFragment       = " IF NOT EXISTS"
	fromFragment              = " FROM "
	limitFragment             = " LIMIT "
	perPartitionLimitFragment = " PER PARTITION LIMIT "
	groupByFragment           = " GROUP BY "
	orderByFragment           = " ORDER BY "
	directionAscFragment      = " ASC"
	directionDescFragment     = " DESC"
	whereFragment             = " WHERE "
	allowFilteringFragment    = " ALLOW FILTERING"
	andFragment               = " AND "
	spaceFragment             = " "
	writetimeFragment         = "WRITETIME"
	maxWritetimeFragment      = "MAXWRITETIME"
	ttlFragment               = "TTL"
	timestampFragment         = "TIMESTAMP"
	openParenFragment         = "("
	closeParenFragment        = ")"
	usingFragment             = " USING "
)
